/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.controls;

import controller.Controller;
import enums.GameState;
import view.GameWindow;

import javax.swing.*;

/**
 *
 * @author Craig Ryan
 */
public class MainMenuPanel extends javax.swing.JPanel
{
    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel()
    {
        initComponents();

        // CODE GOES HERE
        setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLabel = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        levelSelectButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setSize(new java.awt.Dimension(1000, 1000));
        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("PHYZBLOK");
        titleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 0;
        gridBagConstraints.ipady = 0;
        add(titleLabel, gridBagConstraints);

        startGameButton.setText("Start Game");
        startGameButton.setMaximumSize(new java.awt.Dimension(98, 29));
        startGameButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startGameButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(startGameButton, gridBagConstraints);

        levelSelectButton.setText("Level Select");
        levelSelectButton.setMaximumSize(new java.awt.Dimension(98, 29));
        levelSelectButton.setPreferredSize(new java.awt.Dimension(98, 29));
        levelSelectButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                levelSelectButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(levelSelectButton, gridBagConstraints);
    }// </editor-fold>


    private void levelSelectButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        //titleLabel.setText("level select button pressed");
        titleLabel.setText(Controller.getInstance().getState().toString());
        Controller.getInstance().setState(GameState.LEVEL_SELECT);
        //titleLabel.setText(Controller.getInstance().getState().toString());
    }


    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        final Controller c = Controller.getInstance();
        c.setState(GameState.LOADING);
        c.setCurrentLevel(0);
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {

                Controller.getInstance().startCurrentLevel();
            }
        });
    }


    //@Override
    //public void revalidate()
    //{
    //    super.revalidate();
    //    this.setSize(GameWindow.getInstance().getSize());
    //}


    // Variables declaration - do not modify
    private javax.swing.JButton levelSelectButton;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}